---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kind-fhgv0p-system
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./.weave-gitops/clusters/kind-fhgv0p/system
  prune: true
  sourceRef:
    kind: GitRepository
    name: wego-auto-github-test-app-jga6470n

